create database UnidadSalud;

create table UnidadSalud(
id Integer primary key auto_increment,
nombreUnidad text,
codigoUnidad text,
imagen text
);
create table EmpleadosUnidadS(
id Integer primary key auto_increment,
nombreC text not null,
telefono varchar(20) not null,
direccion text not null,
cargo varchar(60) not null,
especialidad varchar(50),
email text not null,
dui varchar(20) not null,
nit varchar(30) not null,
unidadSalud Integer,
Constraint fk_unidadSalud foreign key(unidadSalud) references UnidadSalud(id)
);
create table Doctor(
id Integer primary key auto_increment,
usuario varchar(150),
empleado Integer,
firma text,
sello text,
contraseña varchar(50),
constraint fk_empleado foreign key(empleado) references EmpleadoUnidadS(id)
);
create table FormularioExpedienteClin(
id Integer primary key auto_increment,
nombreEstablecimiento text not null,
noExpediente text not null,
codigoECOF varchar(100) not null,
-- Datos del paciente
noDUI varchar(10),
noPasaporte varchar(20),
nombreCompleto varchar(200) not null,
fechaNacimiento date not null,
edadAños Integer,
edadMeses Integer,
edadDias Integer,
edadHoras Decimal(10,2),
sexo varchar(14) not null,
ocupacion varchar(45),
estadocivil varchar(30) not null,
direccionResidencia text not null,
departamento varchar(100) not null,
municipio varchar(100) not null,
canton varchar(100) not null,
area varchar(100) not null,
nacionalidad varchar(100) not null,
telefono varchar(100),
-- Datos de la familia
nombrePadre varchar(150),
nombreMadre varchar(150),
nombreConyugue varchar(150),
nombreResponsable varchar(150),
direccionResponsable text,
departamentoResponsable varchar(100),
municipioResponsable varchar(100),
telefonoResponsable varchar(50),
-- Datos de quien proporciono informacion del paciente
nombreQuienProporciono varchar(200),
parentesco varchar(100),
documentoIdentificacion varchar(10),
numeroDocumento varchar(50),
responsableTomarInfo varchar(200),
fechaIncripcion datetime,
observaciones text,
UnidadSaludExp Integer,
Constraint Fk_fichaIncripcionAM foreign key(UnidadSaludExp) references UnidadSalud(id)
);
create table FichaDeInscripcionAM
(
	Id integer primary key auto_increment,
    NExpediente text not null,
    Region text not null,
    Sibasi text not null,
    EstablecimientoSalud text not null,
    ResponsableLlenado text not null,
    Fecha datetime not null,
    -- DATOS DE IDENTIFICACION
    Nombre text not null,
    Edad int not null,
    Sexo text not null,
    Direccion text not null,
    Escolaridad text not null,
    Ocupacion text not null,
    Religion text null,
    EstadoCivil text not null,
    Cuidador text,
    NombreCuidador text,
	Familiar text,
    Parentesco text,
    Responsable text,
    OcupacionCuidador text null,
    -- PRESENTE ENFERMEDAD
    PresenteEnfermedad text not null,
    -- ANTECEDENTES PERSONALES
    Diabetes text,
    HTA text,
    Artritis text,
    TB text,
    Cancer text,
    Alcoholismo text,
    Fumador text,
    VacunasAdulto1y2 text,
    VacunasAdulto123R text,
    VacunaAntiinfluenza text,
    FechaCitologia datetime,
    Resultado text not null,
    FechaProstata datetime,
    Resultado text not null,
    UsoMedicamentos text,
    Describa text,
    -- SITUACION SOCIOECONOMICA
    FechaIngresa datetime,
    GrupoFamiliar text,
    TipoVivienda text,
    ServiciosBasicos text,
    -- EXAMEN FISICO
    Peso text,
    Talla text,
    Pulso text,
    PresionArterial text,
    FrecuenciaCardiaca text,
    Temperatura text,
    FrecuenciaRespiratoria text,
    IMC text,
    -- EVALUACION POR SINTOMAS
    Piel text,
    Cabeza text,
    Ojos text,
    Oidos text,
    Nariz text,
    Boca text,
    Cuello text,
    Cardiovascular text,
    Pulmonar text,
    Torax text,
    Mamas text,
    Ultrasonografia text,
    Mamografia text,
    Abdomen text,
    Genitales text,
    MiembrosSuperiores text,
    MiembrosInferiores text,
    Observaciones text,
    EvaluacionFuncional text,
    EvaluacionMental text,
    EvaluacionMarcha text,
	EvaluaiconEstadoAnimo text,
    EvaluacionNutricional text,
    EvaluacionVisual text,
    EvaluacionAuditiva text,
	dolorcronico varchar(50),
intensidadDolor varchar(50),
periodoDolor varchar(50),
lugarDolor varchar(100),
incontinenciaUrinaria varchar(100),
adultoMenAbandono varchar(50),
adultoMconAbusoMaltrato varchar(50),
observaciones text,
-- Odontologia --
presenciaSarrosubOsupragingival text,
inflamacionGingival text,
movilidadDentaria varchar(20),
gradomovilidadDentaria varchar(30),
abrasion varchar(20),
atrision varchar(20),
lesionesCariosas text,
numeroPiezas int,
usoDprotesis varchar(20),
Otros text,
-- Examenes de laboratorio
examenHTyHB datetime,
examenGlicemia datetime,
examenCreatinina datetime,
examenAcidoUrico datetime,
examenETS_VIH datetime,
examenECG datetime,
examenHDL datetime,
examenLDL datetime,
examenColesterol datetime,
examenTrigleceridos datetime,
examenHeces datetime,
examenOrina datetime,
examenHecesmasSangreO datetime,
examenNitrogenoUreico datetime,
examenRxToraxAP datetime,
-- Diagnostico
estadoAdlutorM varchar(20),
tratamiento text,
referenciaA text,
procimaCita datetime,
-- Club a que pertenece
clubAdultosMayores varchar(50),
clubArtriticos varchar(50),
clubHipertensos varchar(50),
clubDiabeticos varchar(50),
otrosClubs varchar(100),
expediente Integer,
Constraint Fk_expediente foreign key(expediente) references FormularioExpedienteClin(id)
);
create table ProgramaAenSdelAdultoMayor(
id Integer primary key auto_increment,
NoExpediente text not null,
region text,
sibasi text not null,
establecimientoDsalud text not null,
personaEncargadaDllenada text not null,
fecha datetime not null,
-- datos de identificacion
fichaInsPrograma_id Integer not null,
CONSTRAINT fk_ficha FOREIGN KEY (fichaInsPrograma_id)
        REFERENCES FichaDeInscripcionAM(id),
nombreDelCuidador varchar(100),
-- Consulta por
consultaPor text,
-- Examen fisico
peso Decimal(10,2),
talla Decimal(10,2),
pulso varchar(50),
presionArterial varchar(50),
frecuenciaCardiaca varchar(50),
temperatura varchar(50),
frecuenciaRespiratoria varchar(50),
IMC varchar(50),
-- Evaluacion por sistemas
evaluacionpiel varchar(50),
evaluacioncabeza varchar(50),
evaluacionojos varchar(50),
evaluacionoidos varchar(50),
evaluacionnariz varchar(50),
evaluacionboca varchar(50),
evaluacioncuello varchar(50),
evaluacionCardiovascular varchar(50),
evaluacionPulmonar varchar(50),
evaluacionMamas varchar(50),
evaluacionUltrasonografia varchar(50),
evaluacionMamografia varchar(50),
evaluacionAbdomen varchar(50),
evaluacionGenitales varchar(50),
evaluacionMiembrosSuperiores varchar(50),
evaluacionMiembrosInferiores varchar(50),
observaciones text,
evaluacionFuncionales varchar(50),
evaluacionMental varchar(50),
evaluacionMarcha varchar(50),
evaluacionEstadoAnimo varchar(50),
evaluacionNutricional varchar(50),
evalucaionVisual varchar(50),
evaluacionAuditiva varchar(50),
-- Desde dolor cronico hasta Proxima cita
 dolorcronico varchar(50),
intensidadDolor varchar(50),
periodoDolor varchar(50),
lugarDolor varchar(100),
incontinenciaUrinaria varchar(100),
adultoMenAbandono varchar(50),
adultoMconAbusoMaltrato varchar(50),
observaciones text,
-- Odontologia --
presenciaSarrosubOsupragingival text,
inflamacionGingival text,
movilidadDentaria varchar(20),
gradomovilidadDentaria varchar(30),
abrasion varchar(20),
atrision varchar(20),
lesionesCariosas text,
numeroPiezas int,
usoDprotesis varchar(20),
Otros text,
-- Examenes de laboratorio
examenHTyHB datetime,
examenGlicemia datetime,
examenCreatinina datetime,
examenAcidoUrico datetime,
examenETS_VIH datetime,
examenECG datetime,
examenHDL datetime,
examenLDL datetime,
examenColesterol datetime,
examenTrigleceridos datetime,
examenHeces datetime,
examenOrina datetime,
examenHecesmasSangreO datetime,
examenNitrogenoUreico datetime,
examenRxToraxAP datetime,
-- Diagnostico
estadoAdlutorM varchar(20),
tratamiento text,
referenciaA text,
procimaCita datetime
);

-- continuacion

create table FAntecedentesMedicos(
id Integer primary key auto_increment,
NombreEstablecimiento varchar(100),
    NombrePaciente varchar(100),
    FechaLlenado datetime,
    NumeroExpediente varchar(100),
    -- ANTECEDENTES FAMILIARES
    -- PATOLOGIAS
    HipertensionArterial varchar(20),
    HAParentesco varchar(100),
    Diabetes varchar(20),
    DParentesco varchar(100),
    AsmaBronquial varchar(20),
    ABParentesco varchar(100),
    TrastornosMentales varchar(20),
    TMParentesco varchar(100),
    Cancer varchar(20),
    CParentesco varchar(100),
    Otros varchar(20),
    OParentesco varchar(100),
    -- ANTECEDENTES PERSONALES
    -- EVENTOS
    FumaActualmente varchar(20),
    CigarrosPorDia varchar(20),
    AnioFumando varchar(20),
    FumoAlgunaVez varchar(20),
    AniosDejoDeFumar varchar(20),
    ContactoConFumadores varchar(20),
    Lugar varchar(100),
    TomaAlcohol varchar(20),
    BebidaDia varchar(20),
    VecesSemana varchar(20),
    AniosTomando varchar(20),
    UsaDrogasSustancias varchar(20),
    ReaccionesAdbersasMedicamentos varchar(20),
    Cirugias varchar(20),
    TraumatismosSeveros varchar(20),
    HipertensionArterial varchar(20),
    DiabetesMellitus varchar(20),
    Hipertiroidismo varchar(20),
    Hipotiroidismo varchar(20),
    Dislipidemia varchar(20),
    UlceraGastrica varchar(20),
    EnfermedadAcidoPeptica varchar(20),
    Epilepsia varchar(20),
    EnfermedadPulmonar varchar(20),
    EfermedadRenal varchar(20),
    ParalisisFraccida varchar(20),
    Dengue varchar(20),
    InfeccionesTransmisionSexual varchar(20),
    Chagas varchar(20),
    Tuberculosis varchar(20),
    Alergia varchar(20),
    OtraEnfermedadCardiovascular varchar(20),
    Cancer2 varchar(20),
    TrastornosMentalesComportamiento varchar(20),
    EnfermedadesEruptivas varchar(20),
    EnfermedadBucodental varchar(20),
    Artritis varchar(20),
    Colagenopatias varchar(20),
    Discapacidad varchar(20),
    AccidenteCerebrovascular varchar(20),
-- Historia gineco-obstetrica
edadMenarquia Integer,
patronMenstrual varchar(50),
edadRelacionesSexuales Integer,
anteUsoMetodosProteccion varchar(20),
tipoAnticonceptivo varchar(100),
esterilizacion varchar(20),
observacionesGO varchar(50),
-- Antecedentes de violencia
violenciaPsicologica varchar(20),
violenciaFisica varchar(20),
violenciaAutoinflingida varchar(20),
victmaAbandono varchar(20),
victimaTrataPersonas varchar(20),
observcaionesViolencia varchar(50),
-- Riesgo laboral
ocupacion varchar(150),
riesgoLaboral varchar(20),
tipoExposicion varchar(150),
-- Esquema de vacunacion
vacunaBCG1raD varchar(20),
vacunaBCG2daD varchar(20),
vacunaBCG3raD varchar(20),
vacunaBCG1erR varchar(20),
vacunaBCG1doR varchar(20),
vacunaOPV1raD varchar(20),
vacunaOPV2daD varchar(20),
vacunaOPV3raD varchar(20),
vacunaOPV1erR varchar(20),
vacunaOPV2doR varchar(20),
vacunaPentavalente1raD varchar(20),
vacunaPentavalente2daD varchar(20),
vacunaPentavalente3raD varchar(20),
vacunaPentavalente1erR varchar(20),
vacunaPentavalente2doR varchar(20),
vacunaSPR1raD varchar(20),
vacunaSPR2daD varchar(20),
vacunaSPR3raD varchar(20),
vacunaSPR1erR varchar(20),
vacunaSPR2doR varchar(20),
vacunaDPT1raD varchar(20),
vacunaDPT2daD varchar(20),
vacunaDPT3raD varchar(20),
vacunaDPT1erR varchar(20),
vacunaDPT2doR varchar(20),
vacunaInfluenza1raD varchar(20),
vacunaInfluenza2daD varchar(20),
vacunaInfluenza3raD varchar(20),
vacunaInfluenza1erR varchar(20),
vacunaInfluenza2doR varchar(20),
vacunaRotavirus1raD varchar(20),
vacunaRotavirus2daD varchar(20),
vacunaRotavirus3raD varchar(20),
vacunaRotavirus1erR varchar(20),
vacunaRotavirus2doR varchar(20),
vacunaNeumococoI1raD varchar(20),
vacunaNeumococoI2daD varchar(20),
vacunaNeumococoI3raD varchar(20),
vacunaNeumococoI1erR varchar(20),
vacunaNeumococoI2doR varchar(20),
vacunaTd1raD varchar(20),
vacunaTd2daD varchar(20),
vacunaTd3raD varchar(20),
vacunaTd1erR varchar(20),
vacunaTd2doR varchar(20),
vacunaHB1raD varchar(20),
vacunaHB2daD varchar(20),
vacunaHB3raD varchar(20),
vacunaHB1erR varchar(20),
vacunaHB2doR varchar(20),
vacunaSR1raD varchar(20),
vacunaSR2daD varchar(20),
vacunaSR3raD varchar(20),
vacunaSR1erR varchar(20),
vacunaSR2doR varchar(20),
vacunaNeumococo23V1raD varchar(20),
vacunaNeumococo23V2daD varchar(20),
vacunaNeumococo23V3raD varchar(20),
vacunaNeumococo23V1erR varchar(20),
vacunaNeumococo23V2doR varchar(20),
expediente Integer,
Constraint Fk_expediente foreign key(expediente) references FormularioExpedienteClin(id)
);
create table TamizajeViolencia(
id Integer primary key auto_increment,
pacientenombre varchar(100),
pregunta1T varchar(20),
pregunta2T varchar(20),
pregunta3T varchar(20),
pregunta4T varchar(20),
pregunta5T varchar(20),
pregunta6T varchar(20),
pregunta7T varchar(20),
-- preguntas que complementan el tamizaje de violencia
pregunta8T varchar(20),
pregunta9T varchar(20),
pregunta10T varchar(20),
pregunta11T varchar(20),
pregunta12T varchar(20),
pregunta13T varchar(20),
pregunta14T varchar(20),
pregunta15T varchar(20),
pregunta16T varchar(20),
pregunta17T varchar(20),
pregunta18T varchar(20),
pregunta19T varchar(20),
pregunta20T varchar(20),
pregunta21T varchar(20),
pregunta22T varchar(20),
pregunta23T varchar(20),
pregunta24T varchar(20),
-- diagnostico de abuso emocional en la mujer o cualquier otro miembro en la familia
pregunta1A varchar(20),
pregunta2A varchar(20),
pregunta3A varchar(20),
pregunta4A varchar(20),
pregunta5A varchar(20),
pregunta6A varchar(20),
antecedenteMedicos Integer,
Constraint Fk_antecedenteMedicos foreign key(antecedenteMedicos) references FAntecedentesMedicos(id)
);
-- 
create table HistoriaClinicaHyM20a59(
id integer primary key auto_increment,
-- Datos generales
edad Integer not null,
estadoCivil varchar(50),
nombre varchar(150),
sexo varchar(30),
ocupacionActual varchar(50),
escolaridad varchar(70),
peso Decimal(10,2),
talla Decimal(10,2),
IMC varchar(50),
-- Factores de riesgo
consumoTabaco varchar(20),
sobrepeso varchar(20),
consumoAlcohol varchar(20),
desnutricion varchar(20),
Sedentarismo varchar(20),
automedicacion varchar(20),
-- Historia de salud medica
edadRelacionesSexuales integer,
noParejasSexuales varchar(20),
usoPreservativos varchar(30),
disfuncionesSexuales varchar(40),
padecimientoITS varchar(30),
noHijos Integer,
esterilizado varchar(20),
metodoPlanificacion varchar(20),
-- Antecedentes de salud general y morbilidad
diabetes varchar(20),
dislipidemia varchar(20),
Acidopeptica varchar(20),
prostatitis varchar(20),
HTA varchar(20),
IVU varchar(20),
ColonIrritable varchar(20),
CAProstata varchar(20),
Artritis varchar(20),
Neumonia varchar(20),
HiperProstBEN varchar(20),
CACervixMama varchar(20),
clubDiabeticos varchar(20),
clubHipertensos varchar(20),
examenProstata varchar(30),
ultimaRealizacion varchar(30),
citologiaUltima varchar(30),
refuerzoVacunaTd varchar(20),
caries varchar(20),
enfermedadPeridontal varchar(20),
estaEnTX varchar(20),
profilaxisAlgunaVez varchar(20),
consultaSubsecuenteHyM20a59 Integer,
CONSTRAINT fk_consulta FOREIGN KEY (consultaSubsecuenteHyM20a59)
        REFERENCES ConsultaSubsecuenteHyM20a59(id)
);


create table ConsultaSubsecuenteHyM20a59(
id Integer primary key auto_increment,
motivoConsulta varchar(200),
HXpresenteEnfermedad text,
-- Examen fisico
presionArterial varchar(20),
pulso varchar(20),
frecuenciaRespiratoria varchar(20),
impresionDiagnostica text,
tratamientoConsejeria text,
referencia varchar(50),
firmaResponsable text,
sello text,
responsable varchar(30),
historia20a59 Integer,
Constraint Fk_ehistoria20a59 foreign key(historia20a59) references HistoriaClinicaHyM20a59(id)
);

create table EvaluacionAlimentacion(
id Integer primary key auto_increment,
tomaPecho varchar(20),
vecesAlDia Integer,
tieneBuenaPosicion varchar(20),
tieneBuenAgarre varchar(20),
ingiereOalimentacion varchar(20),
vecesAlDiaOA Integer,
cualesAlimentos Varchar(150),
tomaPacha varchar(20),
huboCambioNalimentacion varchar(20),
desdecuando datetime,
-- Control odontologico
estaEncontrolOdont varchar(20),
dolorDental varchar(20),
AbscesoMucosaCdiente varchar(20),
piezaDentalDestruidaSDolor varchar(20),
presenciaFistulaIoE varchar(20),
enciaInflamada varchar(20),
piezaManchada varchar(20),
vesiculasDolorosas varchar(20),
dienteDesalojadoAD varchar(20),
dienteScaries varchar(20),
malAliento varchar(20),
-- evaluar anemia
evaluarTieneAnemia varchar(20),
palidezPalmar varchar(20),
hemoglobina varchar(50),
-- Evaluar si presenta malnutricion
desnutricion varchar(20),
desnutriconSevera varchar(20),
tipoDesnutricion varchar(30),
obesidad varchar(20),
sobrepeso varchar(20),
tendenciaCrece varchar(30)
);
create table EvaluacionDesarrollo(
id Integer primary key auto_increment,
desarrolloniñao varchar(25),
-- validar riesgo
SriesgoCual varchar(150),
-- verificar expediente
vitaminaA varchar(20),
fechaUdosis date,
hierro varchar(40),
fechaUdosisH date,
multivitaminas varchar(20),
fechaUdosisM date,
mebendazo varchar(20),
fechaMebendazo date,
hallazgosHC text,
-- examen fisico
-- revision y descripcion por organos y sistemas
cabezaCuello text,
toraxPulmonar text,
cardica text,
abdomen text,
genitales text,
musculoEsqueletico text,
pielAnexos text,
neurologico text,
vesquemaVacunacion varchar(20),
sufreMaltratoSexual varchar(20),
tipoMaltrato varchar(120),
cumplenDerechos varchar(20),
cualderechoNoCumple varchar(20),
clasificacion varchar(120),
referencia varchar(20),
diagnosticoClinico varchar(120),
diagnosticoNutricional varchar(120),
tratamiento text,
riegoSocial varchar(20),
recomendaciones text,
fechaProxCita datetime,
fechaProxiControl datetime,
sello text,
firma text
);


-- pág 14 
create table HojaSubsecuenteANiñao2a5(
id Integer primary key auto_increment,
nombre varchar(100) not null,
noExpediente text,
fechaConsulta datetime not null,
fechaNacimiento date not null,
edad Integer not null,
sexo varchar(30) not null,
motivoConsulta varchar(150),
-- aun estoy en dudad con los siguientes dos campos 
controlSubsecuente varchar(20),
morbilidad varchar(20),
-- signos vitales y somatometria
FC varchar(100),
FR varchar(100),
TA varchar(100),
peso Decimal(10,2),
temperatura Decimal(10,2),
Longitud Decimal(10,2),
PC varchar(100),
-- Evaluar signos de peligro
evaluacionNopuedebeber varchar(20),
evaluacionConvulsiones varchar(20),
evaluacionLetargico varchar(20),
evaluacionVomitaTodo varchar(20),
enfermedadGrave varchar(20),
niñoTosOdRespirar varchar(20),
cuantoTiempohace varchar(100),
noRespiracionesSeg varchar(30),
rapidaRespiracion varchar(20),
tirajeSubcostal varchar(20),
estridorResposo varchar(20),
sibilancias varchar(20),
niñoDiarrea varchar(20),
cuantoTiempoD varchar(20),
sangreHeces varchar(20),
noEvacuaciones24H Integer,
vomito varchar(20),
novomitos24H Integer,
estaDeshidratadoniño varchar(20),
-- Si la respuesta es si evaluar
-- Estado de conciencia
letargico varchar(20),
inquieto varchar(20),
-- Sed
bbMaloNpuede varchar(20),
bbAvidamente varchar(20),
-- Ojos
ojosHundidos varchar(20),
-- signo de pliegue cutaaneo
desapareceLentmas2seg varchar(20),
desapareceLentmenos2seg varchar(20),
tieneFiebreniño varchar(20),
tiempoFiebreniño varchar(20),
mas7DiasF varchar(20),
todosDias varchar(20),
rigidezCuello varchar(20),
areaHiperPaludismo varchar(20),
areaHiperDengue varchar(20),
-- dengue hemorragico
verificarDAdbomen varchar(20),
verificarEmental varchar(20),
verificardFHipotermia varchar(20),
verificarSangreespon varchar(20),
verificarCianosis varchar(20),
verificarVomitos varchar(20),
verificarEdema varchar(20),
verificarComorbilidad varchar(20),
-- Dengue clasico
verificarMialgias varchar(20),
verificarCefalea varchar(20),
verificarAnorexia varchar(20),
verificarExantema varchar(20),
verificarmalGenDolor varchar(20),
verificarPruebaLao varchar(20),
-- Sarampion
erupcionCutanea varchar(20),
tieneProbOidoniño varchar(20),
tumefaccionDorejas varchar(20),
membranaHiperemica varchar(20),
supuracionVOidoMa14d varchar(20),
supuracionVOidoMe14d varchar(20),
dolorOido varchar(20),
tieneProbGargantaniño varchar(20),
gangliosDolorosos varchar(20),
exudadoBlanco varchar(20),
eritematosaGarganta varchar(20),
DolorGarganSganglios varchar(20),
evaluarAlimentacion Integer,
CONSTRAINT fk_Alimentacion FOREIGN KEY (evaluarAlimentacion)
        REFERENCES EvaluacionAlimentacion(id),
evaluarDesarrollo Integer,
CONSTRAINT fk_Desarrollo FOREIGN KEY (evaluarDesarrollo)
        REFERENCES EvaluacionDesarrollo(id)

);

CREATE table HojaOdontologicaAtencionMenos5anios
(
    idHojaOndologica integer primary key auto_increment,
    Nombre varchar(100),
    NumeroRegistro varchar(100),
    Establecimiento varchar(100),
    Sexo varchar(50),
    FechaNacimiento date,
    FechaInscripcion datetime,
    Edad int,
    Peso decimal(10,2),
    TemperaturaCelcius decimal(10,2),
    MotivoConsulta varchar(100),
    -- NINO MENOR DE 8 DIAS
    FisuraLabial varchar(20),
    DientesNatales varchar(20),
    DientesNeonatales varchar(20),
    MoniliasisOral varchar(20),
    NingunSignoInfeccion varchar(20),
    RecienNacidoConRiesgo varchar(20),
    RecienNacidoSinRiesgo varchar(20),
    RecienNacidoBocaSana varchar(20),
    -- ODONTOGRAMA (FALTA AUN)
    
    FisuraLabial2 varchar(20),
    DientesNatales2 varchar(20),
    DientesNeonatales2 varchar(20),
    MoniliasisOral2 varchar(20),
    DolorDentalIntenso varchar(20),
    TumefaccionCara varchar(20),
    PiezaDentalDestruidaSinDolor varchar(20),
    PresenciaFistula varchar(20),
    DolorDental varchar(20),
    PiezaConMancha varchar(20),
    UlceracionTejidosBlandos varchar(20),
    EnciaInflamadaConHematoma varchar(20),
    DienteDesalojado varchar(20),
    DienteSinCaries varchar(20),
    MalAliento varchar(20),
    DientesEnciasSanas varchar(20),
    OtrasAlteraciones varchar(20),
    OtrosHallazgos varchar(100),
    Diagnostico varchar(100),
    -- EVALUAR ALIMENTACION SEGUN EDAD
    LactanciaMaterna varchar(20),
    Exclusiva varchar(20),
    Predominante varchar(20),
    Complementaria varchar(20),
    UsoDePacha varchar(20),
    FormulasLeche varchar(20),
    BebidasAzucaradas varchar(20),
    BebidasCarbonatadas varchar(20),
    IngiereOtraAlimentacion varchar(20),
    Cuales varchar(100),
    -- EVALUAR HIGIENE ORAL
    DuermeConPacha varchar(20),
    UtilizaCepilloDental varchar(20),
    EsDeUsoPersonal varchar(20),
    SeCepillaSolo varchar(20),
    RiesgoSocial varchar(20),
    UsaPastaDental varchar(20),
    SeTragaPastaDental varchar(20),
    UtilizaOtroAditivo varchar(20),
    Referencia varchar(20)    
);
create table ControlSubsecuente8DaMenor2M(
id Integer primary key auto_increment,
nombre varchar(150),
tipoControl varchar(30),
registro varchar(100),
fecha datetime,
fechaNacimiento date,
edad Integer,
sexo varchar(30),
partoAtendidoEn varchar(20),
partoAtendidoPor varchar(30),
quienAtendioParto varchar(150),
FC varchar(35),
FR varchar(35),
TA varchar(35),
temperatura varchar(35),
peso varchar(35),
talla varchar(35),
PC varchar(35),
consultaPor varchar(150),
-- Antecedentes perinatales
edadMadre Integer,
formulaOB varchar(35),
-- Duda sobre mas campos
USGOB varchar(20),
controlPrenatal varchar(20),
enferOmedicamentosEmba varchar(150),
RPMmenorq18H varchar(10),
RPMmayorq18H varchar(10),
IVUreciente varchar(10),
contaminadoChecesMat varchar(10),
EnfInfecciosaMat varchar(10),
fiebremayorq38 varchar(10),
partoProlongado varchar(10),
presentacion varchar(10),
viaParto varchar(10),
presentacionMeconio varchar(10),
embarazoPretermino varchar(14),
embarazoMultiple varchar(14),
fecha date,
hora timestamp,
lugarNacimiento text,
pesoNaci Decimal(10,2),
tallaNaci Decimal(10,2),
EGNaci varchar(50),
PCnaci varchar(50),
reanimacionAlnac varchar(20),
apagarmin varchar(20),
cortoCordon varchar(50),
ligoCorgon varchar(50),
BCGNaci varchar(20),
-- Clasificacion por peso y edad
edadGestacional varchar(45),
peso varchar(45),
prematurocsRiesgo varchar(45),
-- bajo peso al nacer
pesobajocsRiesgo varchar(30),
prematuroRiego varchar(10),
bajopesoRiesgo varchar(10),
datosHclinica text

);
create table EvaluarSignosEnfermedadMG(
id Integer primary key auto_increment,
evaluarLetargico varchar(10),
evaluarHipoactivo varchar(10),
evaluarMovAnormales varchar(10),
evaluarIrritable varchar(10),
evaluarCvMal varchar(10),
evaluarMamaMal varchar(10),
evaluarAbombamiento varchar(10),
evaluarFRmena40omaya60 varchar(10),
evaluarTirajesubcostal varchar(10),
evaluarAleteoNasal varchar(10),
evaluarApnea varchar(10),
evaluarQuejido varchar(10),
evaluarCianosis varchar(10),
evaluarTemAxila varchar(10),
evaluarPalidez varchar(10),
evaluarLlenCap varchar(10),
evaluarManifes varchar(10),
evaluarAnomalias varchar(10),
evaluarpesoMenor varchar(10),
evaluaredadGest varchar(10),
evaluarVomitatodo varchar(10),
evaluarSecrecionPuru varchar(10),
evaluarDistencion varchar(10),
evaluarSupuracion varchar(10),
evaluarPustulas varchar(10),
evaluarictericia varchar(10),
enfermedadMGrave varchar(10),
-- Evaluar signos de infeccion local
evaluarSecrecionConjun varchar(10),
evaluarOmbligo varchar(10),
evaluarPustulasPiel varchar(10),
evaluarPlacasBlanque varchar(10),
infeccionLocal varchar(10),
tieneNiñoDiarrea varchar(10),
cuantoTiempoHace Integer,
sangreNheces varchar(10),
noEvacuaciones Integer,
vomitos varchar(10),
noVomitos Integer,
-- Deshidratado
estaDeshidratado varchar(10),
-- estado de conciencia
letargico varchar(10),
inquito varchar(10),
-- sed
bbMalOnPuede varchar(10),
bbAvidadmente varchar(10),
-- ojos
ojoshundidos varchar(10),
-- signo de pliegue cutáneo
desapareceMLent varchar(10),
desapareceLent varchar(10),
-- presenta ictericia
presentaIctericia varchar(10),
inicio24HV varchar(10),
madreRgNegativa varchar(10),
ingestionMedica varchar(10),
zona3omasKramer varchar(10),
hipertonia varchar(10),
-- dato borroso llanto agudo y monótono
llantoMono varchar(10),
cefalohematomas varchar(10),
zona1 varchar(50),
zona2 varchar(50),
zona3 varchar(50),
zona4 varchar(50),
zona5 varchar(50),
ictericinaAltoRiesgo varchar(10),
controlSubsecuente Integer,
Constraint Fk_controlSubsecuente foreign key(controlSubsecuente)
			references ControlSubsecuente8DaMenor2M(id)
);
-- SIGUIENTE TABLA RESPECTO A LA INSCRIPCION O CONTROL SUBSECUENTE DE 8 DIAS A 2 MESES

Create table IcteAlimentacion(
id Integer primary key auto_increment,
evaluarinicio varchar(10),
evaluarSignoNeuro varchar(10),
evaluarClasKramer varchar (10),
ictBajoR varchar(10),
-- Evaluar alimentacion del recien nacido
alimentaPecho varchar(10),
malaSuccion varchar(10),
malAgarre varchar(10),
malaPosicion varchar(10),
recibeFormula varchar(10),
aliPechoMenos12 varchar(10),
piezaDentalNac varchar(10),
alteraInfeccOral varchar(10),
aparienciagen varchar(50),
edemas varchar(10),
Mucosas varchar(20),
color varchar(15),
otrosHallazgos text,
cabYcuello text,
torYpulmonar text,
cardiaco text,
abdomen text,
genitales text,
muscEsqueletico text,
pielYanexos text,
caderas varchar(30),
neurologicos text,
malformaciones text,
evaluarDesarrollo varchar(25),
existeRiesgo varchar(100),
verificarvacuna varchar(10),
evaluarMaltrato varchar(10),
tipoMlatrato varchar(100),
evaluarDerechos varchar(10),
derechoNoCumple varchar(100),
clasificacion varchar(100),
referencia varchar(10),
diagnosticoCli varchar(100),
tratamiento text,
riesgoSocial varchar(10),
cualReiesgo text,
fechaProximaCita date,
control varchar(100),
sello text,
firmaResponsable text,
controlSubsecuente Integer,
Constraint Fk_controlSubsecuente foreign key(controlSubsecuente)
			references ControlSubsecuente8DaMenor2M(id)
);

-- Hoja de atencion integral en salud del niño de 5 a 9 años
create table AtencionIntegralNino5a9
(
    Id Integer primary key auto_increment,
    Nombre varchar(100),
    NumeroRegistro varchar(100),
    Hora time,
    Establecimiento varchar(100),
    Sexo varchar(20),
    ControlSubsecuente varchar(25),
    Morbilidad varchar(25),
    Fecha date,
    Edad int,
    Peso decimal(10,2),
    Talla decimal(10,2),
    -- NL RT RETSEV
    Temperatura varchar(25),
    -- ANTECEDENTES FAMILIARES
    DM varchar(25),
    HTA varchar(25),
    TB varchar(25),
    ASMA varchar(25),
    Otros varchar(100),
    -- ANTECEDENTES CONTRIBUTORIOS
    ASMA2 varchar(25),
    HTA2 varchar(25),
    Inmunosupresion varchar(25),
    Malnutricion varchar(25),
    Renal varchar(25),
    OtraPatologia varchar(100),
    PacienteCronico varchar(25),
    TiempoTratamientoAnios int,
    -- ANTECEDENTES PERSONALES
    AlergiasConocidas varchar(25),
    Cual varchar(100),
    MedicacionContinua varchar(25),
    Cual varchar(100),
    UsaLentes varchar(25),
    AsisteEscuela varchar(25),
    Escolaridad varchar(25),
    AnotacionesSobreAntecedentes text,
    MotivoConsulta varchar(25),
    SignosVitalesFC varchar(50),
    SignosVitalesFR varchar(50),
    SignosVitalesTA varchar(50),
    -- VERIFIQUE SI HAY SIGNOS O SINTOMAS
    -- NEUROLOGICOS
    Cefalea varchar(25),
    Vomitos varchar(25),
    MovimientosAnormales varchar(25),
    MarchaAlterada varchar(25),
    MareosVerticos varchar(25),
    AlteracionesSencibilidad varchar(25),
    DebilidadMuscular varchar(25),
    PresenciaFiebre varchar(25),
    -- SISTEMATICOS
    Tos varchar(25),
    DificultadRespiratoria varchar(25),
    TraumaMenor24h varchar(25),
    ProblemasOido varchar(25),
    DolorAbdominal varchar(25),
    Diarrea varchar(25),
    AlteracionesDeMiccion varchar(25),
    ProblemaPiel varchar(25),
    -- SIGNOS DE PELIGRO
    MalLenado varchar(25),
    TAmediaMenor80 varchar(25),
    FCmayor110 varchar(25),
    PalidezMarcada varchar(25),
    Clanosis varchar(25),
    AlteracionDeEstado varchar(25),
    SospechaDeMaltrato varchar(25),
    CegadoraAguda varchar(25),
    EnfermedadQueAmeritaReferencia varchar(25),
    Antiparasitario varchar(50),
    -- MicroNutrientes varchar(25),
    AcFolico varchar(25),
    VitA varchar(25),
    Otro varchar(25),
    PresenciaAnemia varchar(25),
    PresenciaCaries varchar(25),
    Hipoacusia varchar(25),
    AgudezaVisual varchar(25),
    EsquemaVacunacion varchar(25),
    OtrasVacunas varchar(25),
    EstadoNutricionalActualIMC varchar(25),
    EstadoNutricional varchar(25),
    ExamenFisico text,
    DiagnosticoFisico varchar(25),
    Tratamiento text,
    ReferenciaOftamologo varchar(25),
    ReferenciaOdontologo varchar(25),
    ReferenciaOtroNivel varchar(25),
    Nivel varchar(25),
    Cual varchar(100),
    FechaUltimosExamenes varchar(25),
    HB varchar(25),
    EGO varchar(25),
    Hto varchar(25),
    EGH varchar(25),
    Recomendaciones varchar(100),
    FechaProximaCita datetime,
    Control varchar(25),
    Sello text,
    Firma text
);

-- HistorialAdolescente

create table HistorialAdolescente
(
	Id Integer primary key auto_increment,
	Establecimiento varchar(15),
	HCno varchar(15),
    ApellidoNombre varchar(100),
    Domicilio varchar(100),
    Localidad varchar(100),
    Codigo varchar(25),
    Tel varchar(10),
    Domicilio varchar(25),
    Mensaje varchar(25),
    LugarNacimiento varchar(100),
    Escuela varchar(100),
    FechaNacimiento date,
    Sexo varchar(25),
    -- CONSULTA PRINCIPAL
    Numero varchar(25),
    Fecha date,
    Edad int,
    -- ACOMPAÑANTE
    Acompañante varchar(25),
    EstadoCivil varchar(25),
    --
    MotivoConsultaAdolescente1 varchar(100),
    Cuadro1 varchar(25),
    MotivoConsultaAdolescente2 varchar(100),
    Cuadro2 varchar(25),
    MotivoConsultaAdolescente3 varchar(100),
    Cuadro3 varchar(25),
    MotivoConsultaAcompañante1 varchar(100),
	CuadroA1 varchar(25),
    MotivoConsultaAcompañante2 varchar(100),
	CuadroA1 varchar(25),
    MotivoConsultaAcompañante3 varchar(100),
	CuadroA1 varchar(25),
    ObservacionesRelevantes text,
    -- ANTECEDENTES PERSONALES
    Perinatales varchar(25),
    CrecimientoNormal varchar(25),
    DesarrolloNormal varchar(25),
    VacunasCompletas varchar(25),
    EnfermedadesCronicas varchar(25),
    EnfermedadesInfectoContagiosas varchar(25),
    AccidentesIntoxicacion varchar(25),
    CirugiaHospitalizacion varchar(25),
    UsoMedicinaSustancia varchar(25),
    TrastornosPsicologicos varchar(25),
    Maltrato varchar(25),
    Judicilaes varchar(25),
    Otros varchar(25),
    ObservacionesAP text,
    -- ANTECEDENTES FAMILIARES
    Diabetes varchar(25),
    Obesidad varchar(25), 
    Cardiovascular varchar(25),
    Alegria varchar(25),
    Infecciones varchar(25),
    Trastornos varchar(25),
    AlcoholDrogas varchar(25),
    ViolenciaIntrafamiliar varchar(25),
    MadreAdolesc varchar(25),
    Judiciales varchar(25),
    Otros varchar(25),
    ObservacionesAF text,
    -- FAMILIA
    -- CONVIVE CON
    Madre varchar(25),
    Padre varchar(25),
    Madrastra varchar(25),
    Padrastro varchar(25),
    Hermanos varchar(25),
    Pareja varchar(25),
    Hijo varchar(25),
    Otros varchar(25),
    -- NIVEL DE INSTITUCION
    Panalfabeto varchar(25),
    Pprimincomp varchar(25),
    Pprimario varchar(25),
    PsecundTecnico varchar(25),
    PunivTercicario varchar(25),
    Manalfabeto varchar(25),
    Mprimincomp varchar(25),
    Mprimario varchar(25),
    MsecundTecnico varchar(25),
    MunivTercicario varchar(25),
    -- TIPO DE TRABAJO
    Pninguno varchar(25),
    Pnoestable varchar(25),
    Pestable varchar(25),
	Mninguno varchar(25),
    Mnoestable varchar(25),
    Mestable varchar(25),
    -- DIAGRAMA FAMILIAR
    DiagramaFamiliar text,
    -- VIVIENDA
    EnergiaElectrica varchar(25),
    Agua varchar(25),
    Excretas varchar(25),
    NumeroCuartos varchar(25),
    ObservacionesVivienda text,
    -- VIVE
    Institucion varchar(25),
    Calle varchar(25),
    Solo varchar(25),
    ComparteCama varchar(25),
    Ocupacion varchar(100),
    PercepcionFamiliar varchar(25),
    Observaciones text,
    -- EDUCACION
    Estudia varchar(10),
    Escolaridad varchar(10),
    Nivel varchar(25),
    GradoCurso varchar(25),
    AniosAprobados varchar(10),
    ProblemasEscuela varchar(10),
    AniosRepetidos varchar(10),
    CausasAniosRepetidos varchar(100),
    DesercionExclusion varchar(10),
    CausasDesercion varchar(100),
    EducacionNoFormal varchar(10),
    CausasEduacacion varchar(100),
    ObservacionesEducacion text,
    -- TRABAJO
    Actividad varchar(25),
    EdadInicioT varchar(10),
    TrabajaHorasSem varchar(10),
    HorarioTrabajo varchar(25),
    RazonTrabajo varchar(25),
    TrabajoLegalizado varchar(10),
    TrabajoInsaluble varchar(10),
    TipoDeTrabajo varchar(100),
    ObservacionesTrabajo text,
    -- VIDA SOCIAL
    Aceptacion varchar(25),
    Novioa varchar(10),
    Amigos varchar(10),
    ActividadGrupal varchar(10),
    DeporteHS varchar(10),
    TVHD varchar(10),
    OtrasActividades varchar(10),
    CualesActividades varchar(100),
    ObservacionesVidaSocial text,
    -- HABITOS
    SuenioNormal varchar(10),
    AlimentacionAdecuada varchar(10),
    ComidadPorDia varchar(10),
    ComidasPorDiaConFamilia varchar(10),
    Tabaco varchar(10),
    EdadInicioTabaco varchar(10),
    Alcohol varchar(10),
    EdadInicioAlcohol varchar(10),
    OtroToxico varchar(10),
    FrecuenciaTipo varchar(50),
    ConduceVehiculo varchar(10),
    CualVehiculo varchar(50),
    ObservacionesHabitos text,
    -- GINECO-HUROLOGICO
    MenarcaEspermaAnio varchar(10),
    MenarcaEspermaMes varchar(10),
    FechaUltimaMenstruacion varchar(10),
    FechaMenstruacion date,
    CiclosRegulares varchar(10),
    Dismenorrea varchar(10),
    FlujoPatologico varchar(10),
    EnfermedadesTransmisionSexual varchar(10),
    CualesEnfermedades varchar(100),
    Embarazo varchar(10),
    Hijos varchar(10),
    Abortos varchar(10),
    -- puede q valla algun dato
    ObservacionesGineco text,
    -- SEXUALIDAD
    NecesitaInformacion varchar(10),
    RelacionesSexuales varchar(25),
    Pareja varchar(25),
    EdadInicioRelSex varchar(10),
    ProblemasRelSex varchar(10),
    Anticoncepcion varchar(25),
    Condon varchar(25),
    AbusoSexual varchar(10),
    ObservacionesSexualidad text,
    -- SITUACION PSICOEMOCIONAL
    ImagenCorporal varchar(50),
    AutoPercepcion varchar(25),
    ReferenteAdulto varchar(25),
    ProyectosDeVida varchar(25),
    ObservacionesPsicoemocional text,
    -- EXAMEN FISICO
    AspectoGeneral varchar(10),
    Peso decimal(10,2),
    Talla decimal(10,2),
    CentilPeso varchar(10),
    CentilTalla varchar(10),
    CentilPesoTalla varchar(10),
	PielFaneras varchar(10),
    Cabeza varchar(10),
    AgudezaVisual varchar(10),
    AgudezaAuditiva varchar(10),
    BocaDientes varchar(10),
    CuelloTiroides varchar(10),
    ToraxMamas varchar(10),
    CardioPulmonar varchar(10),
    PresionArterial varchar(25),
    FrecuenciaCardiaca varchar(25),
    Abdomen varchar(10),
    GenitoUrinario varchar(10),
    Taner varchar(25),
    VolumenTesticularDer varchar(10),
    VolumenTesticularIzq varchar(10),
    Columna varchar(10),
    Extremidades varchar(10),
    Neurologico varchar(10),
    ObservacionesExamenFisico text,
    ImpresionDiagnosticaIntegral text,
    Cuadro1 varchar(10),
    Cuadro2 varchar(10),
    Cuadro3 varchar(10),
    IndicacionesInterconsultas varchar(100),
    Cuadro4 varchar(10),
    Cuadro5 varchar(10),
    Cuadro6 varchar(10),
    Responsable varchar(50),
    Cuadro7 varchar(10),
    FechaProximaVisita date
);
--- CONSULTA INSCRIPCION
Create table ConsultaInscripcion(
id Integer primary key auto_increment,
noExpediente text not null,
fecha datetime not null,
nombre varchar(120) not null,
edad Integer not null,
estadoCivil varchar(30),
ocupacion varchar(50),
direccion text,
incripcion1raVida varchar(10),
inscripcion1raInsti varchar(10),
departamento varchar(50),
municipio varchar(50),
canton varchar(50),
caserio varchar(50),
añosEstudio Integer,
-- Antecedentes obstetricos
noEmbarazos Integer,
partosAterminos Integer,
partosPrema Integer,
abortos Integer,
vivosActualmente Integer,
fechaUEObste date,
lacta varchar(10),
terUEObste varchar(30),
productoVivo varchar(10),
-- Antecedentes Ginecologicos
menarquia Integer,
-- POSIBILIDAD DE DATOS EXTRAS EN LOS SIGUIENTES CAMPOS------------
FUR varchar(20),
dismenorrea varchar(10),
ciclosMenstruales varchar(20),
duracionCiclo Integer,
sangramientos varchar(20),
duracionSangrado Integer,
fechaUPAP date,
resultado text,
observaciones text,
-- ANTECEDENTES PERSONALES CONRTIBUTORIOS
usadoMetodAntiConcep varchar(10),
metodoUsado varchar(100),
cuantoTiempo Integer,
pqDejoUsarlo Varchar(100),
dondeObtuvo Varchar(100),
-- EXAMEN FISICO
temperatura Decimal(10,2),
pulso varchar(30),
peso Decimal(10,2),
TA varchar(10),
mamas varchar(10),
mamasText text,
abdomen varchar(10),
abdomenText text,
miembrosInf varchar(10),
miembrosInfText text,
-- EXAMEN GINECOLOGICO
genitalesExternos varchar(10),
prolapsoUter varchar(10),
grado varchar(50),
vagina varchar(10),
cuelloUter varchar(10),
dolorMovilidad varchar(10),
sangraContacto varchar(10),
tomaPAP varchar(10), 
observaciones text,
uteroPosicion varchar(10),
tamaño varchar(10),
histerometria varchar(10),
movilidad varchar(10),
dolorMovil varchar(10),
anexosLibres varchar(10),
engrosados varchar(10),
dolorpalpacion varchar(10),
tumores varchar(10),
cualesTumores varchar(100),
fondosSaco varchar(10),
-- TAMIZAJE SEGUN CRITERIOS DE ELEGIBILIDAD MEDICA
lactandoPosparto varchar(10),
fuma35años varchar(10),
hipertension varchar(10),
migraña35años varchar(10),
migrañaAura varchar(10),
antecedentesTVP varchar(10),
enfermedadCVC varchar(10),
cardiopatiaIAC varchar(10),
enfermedadCervi varchar(10),
cancerCervico varchar(10),
cancerEndometrial varchar(10),
cancerAmama varchar(10),
enfermedadTrofo varchar(10),
sangradioVI varchar(10),
cirrocisGrave varchar(10),
hepatitisActiva varchar(10),
tumoresHepaticos varchar(10),
cervicitisPACG varchar(10),
enfermedadPIA varchar(10),
-- INFORMACION CLAVE DE LA CONSEJERIA
mecanismoAccion varchar(10),
usoCorrrecto varchar(10),
efectosSecun varchar(10),
tasaEfecti varchar(10),
signosAlarma varchar(10),
seguimiento varchar(10),
-- METODO ENTREGADO
fechaImetodo date,
anticonceptivoO varchar(10),
nombre varchar(50),
DIU varchar(10),
tipoDIU varchar(30),
condones varchar(10),
inyectables varchar(10),
norplant varchar(10),
esterilizaciones varchar(10),
otros varchar(20),
indicaciones varchar(100),
observaciones varchar(200),
fechaProximaCita Date,
-- RESPONSABLE
nombreResponsable text,
firma  text,
sello text
);
-- Se agregaron 2 tablas más
-- Tabla de unidad de atención integral en salud sexual y reproductiva -------

create table AtencionISSYR(
id Integer primary key auto_increment,
nombrePac varchar(100) not null,
noExpediente text not null,
direccion text,
telefono varchar(20),
fecha1ra date,
fecha2da date,
fecha3ra date,
fecha4ta date,
fecha5ta date,
antecedente11er varchar(10),
antecedente12do varchar(10),
antecedente13er varchar(10),
antecedente14to varchar(10),
antecedente15to varchar(10),
antecedente21er varchar(10),
antecedente22do varchar(10),
antecedente23er varchar(10),
antecedente24to varchar(10),
antecedente25to varchar(10),
antecedente31er varchar(10),
antecedente32do varchar(10),
antecedente33er varchar(10),
antecedente34to varchar(10),
antecedente35to varchar(10),
antecedente41er varchar(10),
antecedente42do varchar(10),
antecedente43er varchar(10),
antecedente44to varchar(10),
antecedente45to varchar(10),
antecedente51er varchar(10),
antecedente52do varchar(10),
antecedente53er varchar(10),
antecedente54to varchar(10),
antecedente55to varchar(10),
antecedente61er varchar(10),
antecedente62do varchar(10),
antecedente63er varchar(10),
antecedente64to varchar(10),
antecedente65to varchar(10),
antecedente71er varchar(10),
antecedente72do varchar(10),
antecedente73er varchar(10),
antecedente74to varchar(10),
antecedente75to varchar(10),
antecedente81er varchar(10),
antecedente82do varchar(10),
antecedente83er varchar(10),
antecedente84to varchar(10),
antecedente85to varchar(10),
-- Aqui voy
antecedente91er varchar(10),
antecedente92do varchar(10),
antecedente93er varchar(10),
antecedente94to varchar(10),
antecedente95to varchar(10),
antecedente101er varchar(10),
antecedente102do varchar(10),
antecedente103er varchar(10),
antecedente104to varchar(10),
antecedente105to varchar(10),
antecedente111er varchar(10),
antecedente112do varchar(10),
antecedente113er varchar(10),
antecedente114to varchar(10),
antecedente115to varchar(10),
-- Historia medica general
historiaMG11er varchar(10),
historiaMG12do varchar(10),
historiaMG13er varchar(10),
historiaMG14to varchar(10),
historiaMG15to varchar(10),
historiaMG21er varchar(10),
historiaMG22do varchar(10),
historiaMG23er varchar(10),
historiaMG24to varchar(10),
historiaMG25to varchar(10),
historiaMG31er varchar(10),
historiaMG32do varchar(10),
historiaMG33er varchar(10),
historiaMG34to varchar(10),
historiaMG35to varchar(10),
historiaMG41er varchar(10),
historiaMG42do varchar(10),
historiaMG43er varchar(10),
historiaMG44to varchar(10),
historiaMG45to varchar(10),
historiaMG51er varchar(10),
historiaMG52do varchar(10),
historiaMG53er varchar(10),
historiaMG54to varchar(10),
historiaMG55to varchar(10),
historiaMG61er varchar(10),
historiaMG62do varchar(10),
historiaMG63er varchar(10),
historiaMG64to varchar(10),
historiaMG65to varchar(10),
historiaMG71er varchar(10),
historiaMG72do varchar(10),
historiaMG73er varchar(10),
historiaMG74to varchar(10),
historiaMG75to varchar(10),
enfermedadEspecifique varchar(50),
historiaMG81er varchar(10),
historiaMG82do varchar(10),
historiaMG83er varchar(10),
historiaMG84to varchar(10),
historiaMG85to varchar(10),
-- Embarazo actual 
embarazo91er varchar(10),
embarazo92do varchar(10),
embarazo93er varchar(10),
embarazo94to varchar(10),
embarazo95to varchar(10),
embarazo101er varchar(10),
embarazo102do varchar(10),
embarazo103er varchar(10),
embarazo104to varchar(10),
embarazo105to varchar(10),
embarazo111er varchar(10),
embarazo112do varchar(10),
embarazo113er varchar(10),
embarazo114to varchar(10),
embarazo115to varchar(10),
embarazo121er varchar(10),
embarazo122do varchar(10),
embarazo123er varchar(10),
embarazo124to varchar(10),
embarazo125to varchar(10),
embarazo131er varchar(10),
embarazo132do varchar(10),
embarazo133er varchar(10),
embarazo134to varchar(10),
embarazo135to varchar(10),
embarazo141er varchar(10),
embarazo142do varchar(10),
embarazo143er varchar(10),
embarazo144to varchar(10),
embarazo145to varchar(10),
embarazo151er varchar(10),
embarazo152do varchar(10),
embarazo153er varchar(10),
embarazo154to varchar(10),
embarazo155to varchar(10),
embarazo161er varchar(10),
embarazo162do varchar(10),
embarazo163er varchar(10),
embarazo164to varchar(10),
embarazo165to varchar(10),
embarazo171er varchar(10),
embarazo172do varchar(10),
embarazo173er varchar(10),
embarazo174to varchar(10),
embarazo175to varchar(10),
embarazo181er varchar(10),
embarazo182do varchar(10),
embarazo183er varchar(10),
embarazo184to varchar(10),
embarazo185to varchar(10),
embarazo191er varchar(10),
embarazo192do varchar(10),
embarazo193er varchar(10),
embarazo194to varchar(10),
embarazo195to varchar(10),
embarazo201er varchar(10),
embarazo202do varchar(10),
embarazo203er varchar(10),
embarazo204to varchar(10),
embarazo205to varchar(10),
embarazo211er varchar(10),
embarazo212do varchar(10),
embarazo213er varchar(10),
embarazo214to varchar(10),
embarazo215to varchar(10)
);

create table HistoriaPerinatal(
id integer primary key auto_increment,
nombre varchar(100),
apellido varchar(100),
domicilio text,
localidad varchar(100),
telefono varchar(9),
fechaNaci date,
edad int,
menos15mayor35 varchar(10),
etnia varchar(15),
alfabeta varchar(5),
estudios varchar(25),
aniosmayornivel int,
estadocivil varchar(25),
vivesolo varchar(10),
aniosmayornivel int,
estadocivil varchar(20),
vivesola varchar(5),
lugardecontrolpenatral varchar(20),
lugarpartoaborto varchar(20),
numidentidad varchar(20),
-- ANTECEDENTES
ftbc varchar(5),
fdiabetes varchar(5),
fhipertension varchar(5),
fpreeclampsia varchar(5),
feclampsia varchar(5),
fotracondmedicagrave varchar(5),
ptbc varchar(5),
pdiabetesl varchar(5),
pdiabetesll varchar(5),
pdiabeteslll varchar(5),
phipertension varchar(5),
ppreeclampsia varchar(5),
peclampsia varchar(5),
potracondmedicagrave varchar(5),
cirugiagenitourinaria varchar(5),
infertilidad varchar(5),
cardiopat varchar(5),
nefropatia varchar(5),
violencia varchar(5),
vihmas varchar(5),
-- OBSTETRICOS
gestasprevias varchar(5),
abortos varchar(5),
vaginales varchar(5),
nacidosvivos varchar(5),
viven varchar(5),
embectopico varchar(5),
partos varchar(5),
tresespontaneosconsecutivos varchar(5),
cesareas varchar(5),
nacidosmuertos varchar(5),
muertosunasem varchar(5),
despuesunasem varchar(5),
ultimoprevio1 varchar(5),
ultimoprevio2 varchar(5),
ultimoprevio3 varchar(5),
ultimoprevio4 varchar(5),
antecedentesgemelares varchar(5),
finembarazoanterior date,
menos1anio varchar(5),
embarazoplaneado varchar(5),
fracasometodoanticoncep varchar(25),
-- GESTION ACTUAL
);

create table ConsultasAntenatales(
id Integer primary key auto_increment,
fechacita datetime not null,
edadGest Integer not null,
peso varchar(10),
PA varchar(50),
alturaUterina varchar(40),
presentacion varchar(30),
FCF varchar(30),
movFetales varchar(30),
ProteiNuria varchar(30),
SigExamTrata text,
iniTecni varchar(30),
proximaCita date,
tipoNac varchar(30),
fechaIngreso date,
carne varchar(10),
conPreTotal varchar(10),
hospiEmba varchar(10),
diasHospi Integer,
-- 
corticoide varchar(30),
semanaInicio varchar(20),
iniParto varchar(20),
rotuMembraAnte varchar(20),
fecharotura datetime,
menor37Sem varchar(10),
mayorIgual18Hr varchar(10),
temMayorIgual38G varchar(10),
edadGestsem varchar(10),
edadGestDias varchar(10),
porFUM varchar(10),
porECO varchar(10),
situacionPre varchar(30),
tamañoFeto varchar(10),
acompañanTDP varchar(30),
acompananP varchar(30)
);
-- Siguiente tabla


--- Continuara
