create database UnidadSalud;
create table FormularioExpedienteClin(
id Integer primary key auto_increment,
nombreEstablecimiento text not null,
noExpediente text not null,
codigoECOF varchar(100) not null,
-- Datos del paciente
noDUI varchar(10),
noPasaporte varchar(20),
nombreCompleto varchar(200) not null,
fechaNacimiento date not null,
edadAños Integer,
edadMeses Integer,
edadDias Integer,
edadHoras Decimal(10,2),
sexo varchar(14) not null,
ocupacion varchar(45),
estadocivil varchar(30) not null,
direccionResidencia text not null,
departamento varchar(100) not null,
municipio varchar(100) not null,
canton varchar(100) not null,
area varchar(100) not null,
nacionalidad varchar(100) not null,
telefono varchar(100),
-- Datos de la familia
nombrePadre varchar(150),
nombreMadre varchar(150),
nombreConyugue varchar(150),
nombreResponsable varchar(150),
direccionResponsable text,
departamentoResponsable varchar(100),
municipioResponsable varchar(100),
telefonoResponsable varchar(50),
-- Datos de quien proporciono informacion del paciente
nombreQuienProporciono varchar(200),
parentesco varchar(100),
documentoIdentificacion varchar(10),
numeroDocumento varchar(50),
responsableTomarInfo varchar(200),
fechaIncripcion datetime,
observaciones text
);
create table FichaDeInscripcionAM
(
	Id integer primary key auto_increment,
    NExpediente text not null,
    Region text not null,
    Sibasi text not null,
    EstablecimientoSalud text not null,
    ResponsableLlenado text not null,
    Fecha datetime not null,
    -- DATOS DE IDENTIFICACION
    Nombre text not null,
    Edad int not null,
    Sexo text not null,
    Direccion text not null,
    Escolaridad text not null,
    Ocupacion text not null,
    Religion text null,
    EstadoCivil text not null,
    Cuidador text,
    NombreCuidador text,
	Familiar text,
    Parentesco text,
    Responsable text,
    OcupacionCuidador text null,
    -- PRESENTE ENFERMEDAD
    PresenteEnfermedad text not null,
    -- ANTECEDENTES PERSONALES
    Diabetes text,
    HTA text,
    Artritis text,
    TB text,
    Cancer text,
    Alcoholismo text,
    Fumador text,
    VacunasAdulto1y2 text,
    VacunasAdulto123R text,
    VacunaAntiinfluenza text,
    FechaCitologia datetime,
    Resultado text not null,
    FechaProstata datetime,
    Resultado text not null,
    UsoMedicamentos text,
    Describa text,
    -- SITUACION SOCIOECONOMICA
    FechaIngresa datetime,
    GrupoFamiliar text,
    TipoVivienda text,
    ServiciosBasicos text,
    -- EXAMEN FISICO
    Peso text,
    Talla text,
    Pulso text,
    PresionArterial text,
    FrecuenciaCardiaca text,
    Temperatura text,
    FrecuenciaRespiratoria text,
    IMC text,
    -- EVALUACION POR SINTOMAS
    Piel text,
    Cabeza text,
    Ojos text,
    Oidos text,
    Nariz text,
    Boca text,
    Cuello text,
    Cardiovascular text,
    Pulmonar text,
    Torax text,
    Mamas text,
    Ultrasonografia text,
    Mamografia text,
    Abdomen text,
    Genitales text,
    MiembrosSuperiores text,
    MiembrosInferiores text,
    Observaciones text,
    EvaluacionFuncional text,
    EvaluacionMental text,
    EvaluacionMarcha text,
	EvaluaiconEstadoAnimo text,
    EvaluacionNutricional text,
    EvaluacionVisual text,
    EvaluacionAuditiva text,
	dolorcronico varchar(50),
intensidadDolor varchar(50),
periodoDolor varchar(50),
lugarDolor varchar(100),
incontinenciaUrinaria varchar(100),
adultoMenAbandono varchar(50),
adultoMconAbusoMaltrato varchar(50),
observaciones text,
-- Odontologia --
presenciaSarrosubOsupragingival text,
inflamacionGingival text,
movilidadDentaria varchar(20),
gradomovilidadDentaria varchar(30),
abrasion varchar(20),
atrision varchar(20),
lesionesCariosas text,
numeroPiezas int,
usoDprotesis varchar(20),
Otros text,
-- Examenes de laboratorio
examenHTyHB datetime,
examenGlicemia datetime,
examenCreatinina datetime,
examenAcidoUrico datetime,
examenETS_VIH datetime,
examenECG datetime,
examenHDL datetime,
examenLDL datetime,
examenColesterol datetime,
examenTrigleceridos datetime,
examenHeces datetime,
examenOrina datetime,
examenHecesmasSangreO datetime,
examenNitrogenoUreico datetime,
examenRxToraxAP datetime,
-- Diagnostico
estadoAdlutorM varchar(20),
tratamiento text,
referenciaA text,
procimaCita datetime,
-- Club a que pertenece
clubAdultosMayores varchar(50),
clubArtriticos varchar(50),
clubHipertensos varchar(50),
clubDiabeticos varchar(50),
otrosClubs varchar(100)
	--Gil
);
create table ProgramaAenSdelAdultoMayor(
id Integer primary key auto_increment,
NoExpediente text not null,
region text,
sibasi text not null,
establecimientoDsalud text not null,
personaEncargadaDllenada text not null,
fecha datetime not null,
-- datos de identificacion
fichaInsPrograma_id Integer not null,
CONSTRAINT fk_ficha FOREIGN KEY (fichaInsPrograma_id)
        REFERENCES FichaDeInscripcionAM(id),
nombreDelCuidador varchar(100),
-- Consulta por
consultaPor text,
-- Examen fisico
peso Decimal(10,2),
talla Decimal(10,2),
pulso varchar(50),
presionArterial varchar(50),
frecuenciaCardiaca varchar(50),
temperatura varchar(50),
frecuenciaRespiratoria varchar(50),
IMC varchar(50),
-- Evaluacion por sistemas
evaluacionpiel varchar(50),
evaluacioncabeza varchar(50),
evaluacionojos varchar(50),
evaluacionoidos varchar(50),
evaluacionnariz varchar(50),
evaluacionboca varchar(50),
evaluacioncuello varchar(50),
evaluacionCardiovascular varchar(50),
evaluacionPulmonar varchar(50),
evaluacionMamas varchar(50),
evaluacionUltrasonografia varchar(50),
evaluacionMamografia varchar(50),
evaluacionAbdomen varchar(50),
evaluacionGenitales varchar(50),
evaluacionMiembrosSuperiores varchar(50),
evaluacionMiembrosInferiores varchar(50),
observaciones text,
evaluacionFuncionales varchar(50),
evaluacionMental varchar(50),
evaluacionMarcha varchar(50),
evaluacionEstadoAnimo varchar(50),
evaluacionNutricional varchar(50),
evalucaionVisual varchar(50),
evaluacionAuditiva varchar(50),
-- Desde dolor cronico hasta Proxima cita
 dolorcronico varchar(50),
intensidadDolor varchar(50),
periodoDolor varchar(50),
lugarDolor varchar(100),
incontinenciaUrinaria varchar(100),
adultoMenAbandono varchar(50),
adultoMconAbusoMaltrato varchar(50),
observaciones text,
-- Odontologia --
presenciaSarrosubOsupragingival text,
inflamacionGingival text,
movilidadDentaria varchar(20),
gradomovilidadDentaria varchar(30),
abrasion varchar(20),
atrision varchar(20),
lesionesCariosas text,
numeroPiezas int,
usoDprotesis varchar(20),
Otros text,
-- Examenes de laboratorio
examenHTyHB datetime,
examenGlicemia datetime,
examenCreatinina datetime,
examenAcidoUrico datetime,
examenETS_VIH datetime,
examenECG datetime,
examenHDL datetime,
examenLDL datetime,
examenColesterol datetime,
examenTrigleceridos datetime,
examenHeces datetime,
examenOrina datetime,
examenHecesmasSangreO datetime,
examenNitrogenoUreico datetime,
examenRxToraxAP datetime,
-- Diagnostico
estadoAdlutorM varchar(20),
tratamiento text,
referenciaA text,
procimaCita datetime
);

-- continuacion

create table FAntecedentesMedicos(
id Integer primary key auto_increment,
NombreEstablecimiento varchar(100),
    NombrePaciente varchar(100),
    FechaLlenado datetime,
    NumeroExpediente varchar(100),
    -- ANTECEDENTES FAMILIARES
    -- PATOLOGIAS
    HipertensionArterial varchar(20),
    HAParentesco varchar(100),
    Diabetes varchar(20),
    DParentesco varchar(100),
    AsmaBronquial varchar(20),
    ABParentesco varchar(100),
    TrastornosMentales varchar(20),
    TMParentesco varchar(100),
    Cancer varchar(20),
    CParentesco varchar(100),
    Otros varchar(20),
    OParentesco varchar(100),
    -- ANTECEDENTES PERSONALES
    -- EVENTOS
    FumaActualmente varchar(20),
    CigarrosPorDia varchar(20),
    AnioFumando varchar(20),
    FumoAlgunaVez varchar(20),
    AniosDejoDeFumar varchar(20),
    ContactoConFumadores varchar(20),
    Lugar varchar(100),
    TomaAlcohol varchar(20),
    BebidaDia varchar(20),
    VecesSemana varchar(20),
    AniosTomando varchar(20),
    UsaDrogasSustancias varchar(20),
    ReaccionesAdbersasMedicamentos varchar(20),
    Cirugias varchar(20),
    TraumatismosSeveros varchar(20),
    HipertensionArterial varchar(20),
    DiabetesMellitus varchar(20),
    Hipertiroidismo varchar(20),
    Hipotiroidismo varchar(20),
    Dislipidemia varchar(20),
    UlceraGastrica varchar(20),
    EnfermedadAcidoPeptica varchar(20),
    Epilepsia varchar(20),
    EnfermedadPulmonar varchar(20),
    EfermedadRenal varchar(20),
    ParalisisFraccida varchar(20),
    Dengue varchar(20),
    InfeccionesTransmisionSexual varchar(20),
    Chagas varchar(20),
    Tuberculosis varchar(20),
    Alergia varchar(20),
    OtraEnfermedadCardiovascular varchar(20),
    Cancer2 varchar(20),
    TrastornosMentalesComportamiento varchar(20),
    EnfermedadesEruptivas varchar(20),
    EnfermedadBucodental varchar(20),
    Artritis varchar(20),
    Colagenopatias varchar(20),
    Discapacidad varchar(20),
    AccidenteCerebrovascular varchar(20),
-- Historia gineco-obstetrica
edadMenarquia Integer,
patronMenstrual varchar(50),
edadRelacionesSexuales Integer,
anteUsoMetodosProteccion varchar(20),
tipoAnticonceptivo varchar(100),
esterilizacion varchar(20),
observacionesGO varchar(50),
-- Antecedentes de violencia
violenciaPsicologica varchar(20),
violenciaFisica varchar(20),
violenciaAutoinflingida varchar(20),
victmaAbandono varchar(20),
victimaTrataPersonas varchar(20),
observcaionesViolencia varchar(50),,
-- Riesgo laboral
ocupacion varchar(150),
riesgoLaboral varchar(20),
tipoExposicion varchar(150),
-- Esquema de vacunacion
vacunaBCG1raD varchar(20),
vacunaBCG2daD varchar(20),
vacunaBCG3raD varchar(20),
vacunaBCG1erR varchar(20),
vacunaBCG1doR varchar(20),
vacunaOPV1raD varchar(20),
vacunaOPV2daD varchar(20),
vacunaOPV3raD varchar(20),
vacunaOPV1erR varchar(20),
vacunaOPV2doR varchar(20),
vacunaPentavalente1raD varchar(20),
vacunaPentavalente2daD varchar(20),
vacunaPentavalente3raD varchar(20),
vacunaPentavalente1erR varchar(20),
vacunaPentavalente2doR varchar(20),
vacunaSPR1raD varchar(20),
vacunaSPR2daD varchar(20),
vacunaSPR3raD varchar(20),
vacunaSPR1erR varchar(20),
vacunaSPR2doR varchar(20),
vacunaDPT1raD varchar(20),
vacunaDPT2daD varchar(20),
vacunaDPT3raD varchar(20),
vacunaDPT1erR varchar(20),
vacunaDPT2doR varchar(20),
vacunaInfluenza1raD varchar(20),
vacunaInfluenza2daD varchar(20),
vacunaInfluenza3raD varchar(20),
vacunaInfluenza1erR varchar(20),
vacunaInfluenza2doR varchar(20),
vacunaRotavirus1raD varchar(20),
vacunaRotavirus2daD varchar(20),
vacunaRotavirus3raD varchar(20),
vacunaRotavirus1erR varchar(20),
vacunaRotavirus2doR varchar(20),
vacunaNeumococoI1raD varchar(20),
vacunaNeumococoI2daD varchar(20),
vacunaNeumococoI3raD varchar(20),
vacunaNeumococoI1erR varchar(20),
vacunaNeumococoI2doR varchar(20),
vacunaTd1raD varchar(20),
vacunaTd2daD varchar(20),
vacunaTd3raD varchar(20),
vacunaTd1erR varchar(20),
vacunaTd2doR varchar(20),
vacunaHB1raD varchar(20),
vacunaHB2daD varchar(20),
vacunaHB3raD varchar(20),
vacunaHB1erR varchar(20),
vacunaHB2doR varchar(20),
vacunaSR1raD varchar(20),
vacunaSR2daD varchar(20),
vacunaSR3raD varchar(20),
vacunaSR1erR varchar(20),
vacunaSR2doR varchar(20),
vacunaNeumococo23V1raD varchar(20),
vacunaNeumococo23V2daD varchar(20),
vacunaNeumococo23V3raD varchar(20),
vacunaNeumococo23V1erR varchar(20),
vacunaNeumococo23V2doR varchar(20)
);
create table TamizajeViolencia(
id Integer primary key auto_increment,
pacientenombre varchar(100),
pregunta1T varchar(20),
pregunta2T varchar(20),
pregunta3T varchar(20),
pregunta4T varchar(20),
pregunta5T varchar(20),
pregunta6T varchar(20),
pregunta7T varchar(20),
-- preguntas que complementan el tamizaje de violencia
pregunta8T varchar(20),
pregunta9T varchar(20),
pregunta10T varchar(20),
pregunta11T varchar(20),
pregunta12T varchar(20),
pregunta13T varchar(20),
pregunta14T varchar(20),
pregunta15T varchar(20),
pregunta16T varchar(20),
pregunta17T varchar(20),
pregunta18T varchar(20),
pregunta19T varchar(20),
pregunta20T varchar(20),
pregunta21T varchar(20),
pregunta22T varchar(20),
pregunta23T varchar(20),
pregunta24T varchar(20),
-- diagnostico de abuso emocional en la mujer o cualquier otro miembro en la familia
pregunta1A varchar(20),
pregunta2A varchar(20),
pregunta3A varchar(20),
pregunta4A varchar(20),
pregunta5A varchar(20),
pregunta6A varchar(20)
);
create table ConsultaSubsecuenteHyM20a59(
id Integer primary key auto_increment,
motivoConsulta varchar(200),
HXpresenteEnfermedad text,
-- Examen fisico
presionArterial varchar(20),
pulso varchar(20),
frecuenciaRespiratoria varchar(20),
impresionDiagnostica text,
tratamientoConsejeria text,
referencia varchar(50),
firmaResponsable text,
sello text,
responsable varchar(30)
);
create table HistoriaClinicaHyM20a59(
id integer primary key auto_increment,
-- Datos generales
edad Integer not null,
estadoCivil varchar(50),
nombre varchar(150),
sexo varchar(30),
ocupacionActual varchar(50),
escolaridad varchar(70),
peso Decimal(10,2),
talla Decimal(10,2),
IMC varchar(50),
-- Factores de riesgo
consumoTabaco varchar(20),
sobrepeso varchar(20),
consumoAlcohol varchar(20),
desnutricion varchar(20),
Sedentarismo varchar(20),
automedicacion varchar(20),
-- Historia de salud medica
edadRelacionesSexuales integer,
noParejasSexuales varchar(20),
usoPreservativos varchar(30),
disfuncionesSexuales varchar(40),
padecimientoITS varchar(30),
noHijos Integer,
esterilizado varchar(20),
metodoPlanificacion varchar(20),
-- Antecedentes de salud general y morbilidad
diabetes varchar(20),
dislipidemia varchar(20),
Acidopeptica varchar(20),
prostatitis varchar(20),
HTA varchar(20),
IVU varchar(20),
ColonIrritable varchar(20),
CAProstata varchar(20),
Artritis varchar(20),
Neumonia varchar(20),
HiperProstBEN varchar(20),
CACervixMama varchar(20),
clubDiabeticos varchar(20),
clubHipertensos varchar(20),
examenProstata varchar(30),
ultimaRealizacion varchar(30),
citologiaUltima varchar(30),
refuerzoVacunaTd varchar(20),
caries varchar(20),
enfermedadPeridontal varchar(20),
estaEnTX varchar(20),
profilaxisAlgunaVez varchar(20),
consultaSubsecuenteHyM20a59 Integer,
CONSTRAINT fk_consulta FOREIGN KEY (consultaSubsecuenteHyM20a59)
        REFERENCES ConsultaSubsecuenteHyM20a59(id)
);

create table EvaluacionAlimentacion(
id Integer primary key auto_increment,
tomaPecho varchar(20),
vecesAlDia Integer,
tieneBuenaPosicion varchar(20),
tieneBuenAgarre varchar(20),
ingiereOalimentacion varchar(20),
vecesAlDiaOA Integer,
cualesAlimentos Varchar(150),
tomaPacha varchar(20),
huboCambioNalimentacion varchar(20),
desdecuando datetime,
--Control odontologico
estaEncontrolOdont varchar(20),
dolorDental varchar(20),
AbscesoMucosaCdiente varchar(20),
piezaDentalDestruidaSDolor varchar(20),
presenciaFistulaIoE varchar(20),
enciaInflamada varchar(20),
piezaManchada varchar(20),
vesiculasDolorosas varchar(20),
dienteDesalojadoAD varchar(20),
dienteScaries varchar(20),
malAliento varchar(20),
-- evaluar anemia
evaluarTieneAnemia varchar(20),
palidezPalmar varchar(20),
hemoglobina varchar(50),
-- Evaluar si presenta malnutricion
desnutricion varchar(20),
desnutriconSevera varchar(20),
tipoDesnutricion varchar(30),
obesidad varchar(20),
sobrepeso varchar(20),
tendenciaCrece varchar(30)
);
create table EvaluacionDesarrollo(
id Integer primary key auto_increment,
desarrolloniñao varchar(25),
-- validar riesgo
SriesgoCual varchar(150),
-- verificar expediente
vitaminaA varchar(20),
fechaUdosis date,
hierro varchar(40),
fechaUdosisH date,
multivitaminas varchar(20),
fechaUdosisM date,
mebendazo varchar(20),
fechaMebendazo date,
hallazgosHC text,
-- examen fisico
-- revision y descripcion por organos y sistemas
cabezaCuello text,
toraxPulmonar text,
cardica text,
abdomen text,
genitales text,
musculoEsqueletico text,
pielAnexos text,
neurologico text,
vesquemaVacunacion varchar(20),
sufreMaltratoSexual varchar(20),
tipoMaltrato varchar(120),
cumplenDerechos varchar(20),
cualderechoNoCumple varchar(20),
clasificacion varchar(120),
referencia varchar(20),
diagnosticoClinico varchar(120),
diagnosticoNutricional varchar(120),
tratamiento text,
riegoSocial varchar(20),
recomendaciones text,
fechaProxCita datetime,
fechaProxiControl datetime,
sello text,
firma text
);


-- pág 14 
create table HojaSubsecuenteANiñao2a5(
id Integer primary key auto_increment,
nombre varchar(100) not null,
noExpediente text,
fechaConsulta datetime not null,
fechaNacimiento date not null,
edad Integer not null,
sexo varchar(30) not null,
motivoConsulta varchar(150),
-- aun estoy en dudad con los siguientes dos campos 
controlSubsecuente varchar(20),
morbilidad varchar(20),
-- signos vitales y somatometria
FC varchar(100),
FR varchar(100),
TA varchar(100),
peso Decimal(10,2),
temperatura Decimal(10,2),
Longitud Decimal(10,2),
PC varchar(100),
-- Evaluar signos de peligro
evaluacionNopuedebeber varchar(20),
evaluacionConvulsiones varchar(20),
evaluacionLetargico varchar(20),
evaluacionVomitaTodo varchar(20),
enfermedadGrave varchar(20),
niñoTosOdRespirar varchar(20),
cuantoTiempohace varchar(100),
noRespiracionesSeg varchar(30),
rapidaRespiracion varchar(20),
tirajeSubcostal varchar(20),
estridorResposo varchar(20),
sibilancias varchar(20),
niñoDiarrea varchar(20),
cuantoTiempoD varchar(20),
sangreHeces varchar(20),
noEvacuaciones24H Integer,
vomito varchar(20),
novomitos24H Integer,
estaDeshidratadoniño varchar(20),
-- Si la respuesta es si evaluar
-- Estado de conciencia
letargico varchar(20),
inquieto varchar(20),
-- Sed
bbMaloNpuede varchar(20),
bbAvidamente varchar(20),
-- Ojos
ojosHundidos varchar(20),
-- signo de pliegue cutaaneo
desapareceLentmas2seg varchar(20),
desapareceLentmenos2seg varchar(20),
tieneFiebreniño varchar(20),
tiempoFiebreniño varchar(20),
mas7DiasF varchar(20),
todosDias varchar(20),
rigidezCuello varchar(20),
areaHiperPaludismo varchar(20),
areaHiperDengue varchar(20),
-- dengue hemorragico
verificarDAdbomen varchar(20),
verificarEmental varchar(20),
verificardFHipotermia varchar(20),
verificarSangreespon varchar(20),
verificarCianosis varchar(20),
verificarVomitos varchar(20),
verificarEdema varchar(20),
verificarComorbilidad varchar(20),
-- Dengue clasico
verificarMialgias varchar(20),
verificarCefalea varchar(20),
verificarAnorexia varchar(20),
verificarExantema varchar(20),
verificarmalGenDolor varchar(20),
verificarPruebaLao varchar(20),
-- Sarampion
erupcionCutanea varchar(20),
tieneProbOidoniño varchar(20),
tumefaccionDorejas varchar(20),
membranaHiperemica varchar(20),
supuracionVOidoMa14d varchar(20),
supuracionVOidoMe14d varchar(20),
dolorOido varchar(20),
tieneProbGargantaniño varchar(20),
gangliosDolorosos varchar(20),
exudadoBlanco varchar(20),
eritematosaGarganta varchar(20),
DolorGarganSganglios varchar(20),
evaluarAlimentacion Integer,
CONSTRAINT fk_Alimentacion FOREIGN KEY (evaluarAlimentacion)
        REFERENCES EvaluacionAlimentacion(id),
evaluarDesarrollo Integer,
CONSTRAINT fk_Desarrollo FOREIGN KEY (evaluarDesarrollo)
        REFERENCES EvaluacionDesarrollo(id)

);

CREATE table HojaOdontologicaAtencionMenos5anios
(
    idHojaOndologica integer primary key auto_increment,
    Nombre varchar(100),
    NumeroRegistro varchar(100),
    Establecimiento varchar(100),
    Sexo varchar(50),
    FechaNacimiento date,
    FechaInscripcion datetime,
    Edad int,
    Peso decimal(10,2),
    TemperaturaCelcius decimal(10,2),
    MotivoConsulta varchar(100),
    -- NINO MENOR DE 8 DIAS
    FisuraLabial varchar(20),
    DientesNatales varchar(20),
    DientesNeonatales varchar(20),
    MoniliasisOral varchar(20),
    NingunSignoInfeccion varchar(20),
    RecienNacidoConRiesgo varchar(20),
    RecienNacidoSinRiesgo varchar(20),
    RecienNacidoBocaSana varchar(20),
    -- ODONTOGRAMA (FALTA AUN)
    
    FisuraLabial2 varchar(20),
    DientesNatales2 varchar(20),
    DientesNeonatales2 varchar(20),
    MoniliasisOral2 varchar(20),
    DolorDentalIntenso varchar(20),
    TumefaccionCara varchar(20),
    PiezaDentalDestruidaSinDolor varchar(20),
    PresenciaFistula varchar(20),
    DolorDental varchar(20),
    PiezaConMancha varchar(20),
    UlceracionTejidosBlandos varchar(20),
    EnciaInflamadaConHematoma varchar(20),
    DienteDesalojado varchar(20),
    DienteSinCaries varchar(20),
    MalAliento varchar(20),
    DientesEnciasSanas varchar(20),
    OtrasAlteraciones varchar(20),
    OtrosHallazgos varchar(100),
    Diagnostico varchar(100),
    -- EVALUAR ALIMENTACION SEGUN EDAD
    LactanciaMaterna varchar(20),
    Exclusiva varchar(20),
    Predominante varchar(20),
    Complementaria varchar(20),
    UsoDePacha varchar(20),
    FormulasLeche varchar(20),
    BebidasAzucaradas varchar(20),
    BebidasCarbonatadas varchar(20),
    IngiereOtraAlimentacion varchar(20),
    Cuales varchar(100),
    -- EVALUAR HIGIENE ORAL
    DuermeConPacha varchar(20),
    UtilizaCepilloDental varchar(20),
    EsDeUsoPersonal varchar(20),
    SeCepillaSolo varchar(20),
    RiesgoSocial varchar(20),
    UsaPastaDental varchar(20),
    SeTragaPastaDental varchar(20),
    UtilizaOtroAditivo varchar(20),
    Referencia varchar(20)    
);
create table ControlSubsecuente8DaMenor2M(
id Integer primary key auto_increment,
nombre varchar(150),
tipoControl varchar(30),
registro varchar(100),
fecha datetime,
fechaNacimiento date,
edad Integer,
sexo varchar(30),
partoAtendidoEn varchar(20),
partoAtendidoPor varchar(30),
quienAtendioParto varchar(150),
FC varchar(35),
FR varchar(35),
TA varchar(35),
temperatura varchar(35),
peso varchar(35),
talla varchar(35),
PC varchar(35),
consultaPor varchar(150),
-- Antecedentes perinatales
edadMadre Integer,
formulaOB varchar(35),
-- Duda sobre mas campos
USGOB varchar(20),
controlPrenatal varchar(20),
enferOmedicamentosEmba varchar(150),
RPMmenorq18H varchar(10),
RPMmayorq18H varchar(10),
IVUreciente varchar(10),
contaminadoChecesMat varchar(10),
EnfInfecciosaMat varchar(10),
fiebremayorq38 varchar(10),
partoProlongado varchar(10),
presentacion varchar(10),
viaParto varchar(10),
presentacionMeconio varchar(10),
embarazoPretermino varchar(14),
embarazoMultiple varchar(14),
fecha date,
hora timestamp,
lugarNacimiento text,
pesoNaci Decimal(10,2),
tallaNaci Decimal(10,2),
EGNaci varchar(50),
PCnaci varchar(50),
reanimacionAlnac varchar(20),
apagarmin varchar(20),
cortoCordon varchar(50),
ligoCorgon varchar(50),
BCGNaci varchar(20),
-- Clasificacion por peso y edad
edadGestacional varchar(45),
peso varchar(45),
prematurocsRiesgo varchar(45),
-- bajo peso al nacer
pesobajocsRiesgo varchar(30),
prematuroRiego varchar(10),
bajopesoRiesgo varchar(10),
datosHclinica text

);
create table EvaluarSignosEnfermedadMG(
id Integer primary key auto_increment,
evaluarLetargico varchar(10),
evaluarHipoactivo varchar(10),
evaluarMovAnormales varchar(10),
evaluarIrritable varchar(10),
evaluarCvMal varchar(10),
evaluarMamaMal varchar(10),
evaluarAbombamiento varchar(10),
evaluarFRmena40omaya60 varchar(10),
evaluarTirajesubcostal varchar(10),
evaluarAleteoNasal varchar(10),
evaluarApnea varchar(10),
evaluarQuejido varchar(10),
evaluarCianosis varchar(10),
evaluarTemAxila varchar(10),
evaluarPalidez varchar(10),
evaluarLlenCap varchar(10),
evaluarManifes varchar(10),
evaluarAnomalias varchar(10),
evaluarpesoMenor varchar(10),
evaluaredadGest varchar(10),
evaluarVomitatodo varchar(10),
evaluarSecrecionPuru varchar(10),
evaluarDistencion varchar(10),
evaluarSupuracion varchar(10),
evaluarPustulas varchar(10),
evaluarictericia varchar(10),
enfermedadMGrave varchar(10),
-- Evaluar signos de infeccion local
evaluarSecrecionConjun varchar(10),
evaluarOmbligo varchar(10),
evaluarPustulasPiel varchar(10),
evaluarPlacasBlanque varchar(10),
infeccionLocal varchar(10),
tieneNiñoDiarrea varchar(10),
cuantoTiempoHace Integer,
sangreNheces varchar(10),
noEvacuaciones Integer,
vomitos varchar(10),
noVomitos Integer,
-- Deshidratado
estaDeshidratado varchar(10),
-- estado de conciencia
letargico varchar(10),
inquito varchar(10),
-- sed
bbMalOnPuede varchar(10),
bbAvidadmente varchar(10),
-- ojos
ojoshundidos varchar(10),
-- signo de pliegue cutáneo
desapareceMLent varchar(10),
desapareceLent varchar(10),
-- presenta ictericia
presentaIctericia varchar(10),
inicio24HV varchar(10),
madreRgNegativa varchar(10),
ingestionMedica varchar(10),
zona3omasKramer varchar(10),
hipertonia varchar(10),
-- dato borroso llanto agudo y monótono
llantoMono varchar(10),
cefalohematomas varchar(10),
zona1 varchar(50),
zona2 varchar(50),
zona3 varchar(50),
zona4 varchar(50),
zona5 varchar(50),
ictericinaAltoRiesgo varchar(10),
controlSubsecuente Integer,
Constraint Fk_controlSubsecuente foreign key(controlSubsecuente)
			references ControlSubsecuente8DaMenor2M(id)
);
-- SIGUIENTE TABLA RESPECTO A LA INSCRIPCION O CONTROL SUBSECUENTE DE 8 DIAS A 2 MESES

Create table IcteAlimentacion(
id Integer primary key auto_increment,
evaluarinicio varchar(10),
evaluarSignoNeuro varchar(10),
evaluarClasKramer varchar (10),
ictBajoR varchar(10),
-- Evaluar alimentacion del recien nacido
alimentaPecho varchar(10),
malaSuccion varchar(10),
malAgarre varchar(10),
malaPosicion varchar(10),
recibeFormula varchar(10),
aliPechoMenos12 varchar(10),
piezaDentalNac varchar(10),
alteraInfeccOral varchar(10),
aparienciagen varchar(50),
edemas varchar(10),
Mucosas varchar(20),
color varchar(15),
otrosHallazgos text,
cabYcuello text,
torYpulmonar text,
cardiaco text,
abdomen text,
genitales text,
muscEsqueletico text,
pielYanexos text,
caderas varchar(30),
neurologicos text,
malformaciones text,
evaluarDesarrollo varchar(25),
existeRiesgo varchar(100),
verificarvacuna varchar(10),
evaluarMaltrato varchar(10),
tipoMlatrato varchar(100),
evaluarDerechos varchar(10),
derechoNoCumple varchar(100),
clasificacion varchar(100),
referencia varchar(10),
diagnosticoCli varchar(100),
tratamiento text,
riesgoSocial varchar(10),
cualReiesgo text,
fechaProximaCita date,
control varchar(100),
sello text,
firmaResponsable text,
controlSubsecuente Integer,
Constraint Fk_controlSubsecuente foreign key(controlSubsecuente)
			references ControlSubsecuente8DaMenor2M(id)
);


